from __future__ import annotations

import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PYPROJECT = ROOT / "pyproject.toml"
LOCKFILE = ROOT / "uv.lock"
PRODUCTION_REQUIREMENTS = ROOT / "requirements.txt"
LOCK_GUARD = ROOT / "scripts" / "verify-python-dependency-lock.sh"


def load_pyproject() -> dict:
    with PYPROJECT.open("rb") as file:
        return tomllib.load(file)


def all_declared_dependencies(data: dict) -> list[str]:
    dependencies = list(data["project"].get("dependencies", []))
    for extra_deps in data["project"].get("optional-dependencies", {}).values():
        dependencies.extend(extra_deps)
    return dependencies


def test_dependency_surfaces_are_split_into_expected_extras() -> None:
    project = load_pyproject()["project"]

    assert project.get("dependencies", []) == []

    optional = project["optional-dependencies"]
    assert set(optional) == {"core", "providers", "desktop", "quant", "dev"}

    assert "python-dotenv>=1.0.0" in optional["core"]
    assert "pydantic-settings>=2.0.0" in optional["core"]
    assert "sqlalchemy>=2.0.0" in optional["core"]
    assert "fastapi>=0.109.0" in optional["core"]
    assert "uvicorn[standard]>=0.27.0" in optional["core"]

    assert "efinance>=0.5.5" in optional["providers"]
    assert "akshare>=1.12.0" in optional["providers"]
    assert "tickflow>=0.1.24" in optional["providers"]
    assert any(dep.startswith("longbridge==0.2.74") for dep in optional["providers"])
    assert any(dep.startswith("longbridge>=4.0.5,<5") for dep in optional["providers"])

    assert "lark-oapi>=1.0.0" in optional["desktop"]
    assert "dingtalk-stream>=0.24.3" in optional["desktop"]
    assert "discord.py>=2.0.0" in optional["desktop"]
    assert "PyNaCl>=1.5.0" in optional["desktop"]

    assert "polars>=1.0.0" in optional["quant"]
    assert "pyarrow>=16.0.0" in optional["quant"]
    assert "duckdb>=1.0.0" in optional["quant"]
    assert any(dep.startswith("pyqlib") for dep in optional["quant"])

    assert "pytest>=9.0.0" in optional["dev"]
    assert "ruff>=0.14.0" in optional["dev"]
    assert "black>=25.0.0" in optional["dev"]
    assert "isort>=7.0.0" in optional["dev"]


def test_dependency_declarations_do_not_use_dynamic_git_installs() -> None:
    declarations = all_declared_dependencies(load_pyproject())

    assert declarations
    assert all("git+" not in dependency for dependency in declarations)
    assert all("github.com/ZhuLinsen/alphasift" not in dependency for dependency in declarations)


def test_lock_and_production_requirements_are_checked_in() -> None:
    assert LOCKFILE.exists()
    assert PRODUCTION_REQUIREMENTS.exists()

    requirements_text = PRODUCTION_REQUIREMENTS.read_text(encoding="utf-8")
    assert "This file was autogenerated by uv" in requirements_text
    assert "fastapi==" in requirements_text
    assert "akshare==" in requirements_text
    assert "discord-py==" in requirements_text
    assert "pyqlib==" not in requirements_text
    assert "git+" not in requirements_text
    assert "github.com/ZhuLinsen/alphasift" not in requirements_text


def test_requirements_drift_guard_uses_lock_and_exact_export_surface() -> None:
    guard = LOCK_GUARD.read_text(encoding="utf-8")

    assert "uv lock --check" in guard
    assert "uv export" in guard
    assert "--extra core" in guard
    assert "--extra providers" in guard
    assert "--extra desktop" in guard
    assert "--no-dev" in guard
    assert "--no-emit-project" in guard
    assert "requirements.txt" in guard
    assert "diff -u" in guard
