#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

TMP_REQUIREMENTS="$(mktemp)"
trap 'rm -f "$TMP_REQUIREMENTS"' EXIT

uv lock --check
{
  echo "# This file was autogenerated by uv via scripts/verify-python-dependency-lock.sh."
  echo "# Do not edit manually; run this script after dependency changes."
  uv export \
    --extra core \
    --extra providers \
    --extra desktop \
    --no-dev \
    --no-emit-project \
    --no-hashes \
    --no-header
} > "$TMP_REQUIREMENTS"

diff -u requirements.txt "$TMP_REQUIREMENTS"
