"""Formal portfolio backtest contracts.

SAL-P4-003 defines the immutable BacktestSpec. SAL-P4-004 adds the compact
BacktestArtifact output contract and SAL-P4-009 adds the pure Portfolio Ledger
accounting contract. SAL-P4-010 adds pure cost/slippage calculations.
SAL-P4-011 adds pure A-share execution rules. Risk evaluation and APIs are
introduced by later P4 tasks.
"""

from serenity_alpha_lab.quant.backtest.costs import (
    BACKTEST_COST_MODEL_CONTRACT_VERSION,
    BACKTEST_COST_MODEL_SCHEMA_NAME,
    BACKTEST_COST_MODEL_SCHEMA_VERSION,
    BACKTEST_COST_MODEL_VERSION,
    CostBreakdown,
    CostLineItem,
    CostLineItemName,
    CostModel,
    CostModelError,
)
from serenity_alpha_lab.quant.backtest.execution import (
    A_SHARE_EXECUTION_MODEL_CONTRACT_VERSION,
    A_SHARE_EXECUTION_MODEL_SCHEMA_NAME,
    A_SHARE_EXECUTION_MODEL_SCHEMA_VERSION,
    A_SHARE_EXECUTION_MODEL_VERSION,
    AShareExecutionAuditRecord,
    AShareExecutionError,
    AShareExecutionModel,
    AShareExecutionOutcome,
    AShareExecutionResult,
    AShareExecutionStatus,
    AShareMarketSnapshot,
    ASharePositionAvailability,
)
from serenity_alpha_lab.quant.backtest.artifacts import (
    BACKTEST_ARTIFACT_BUNDLE_CONTENT_TYPE,
    BACKTEST_ARTIFACT_BUNDLE_SCHEMA_NAME,
    BACKTEST_ARTIFACT_BUNDLE_SCHEMA_VERSION,
    BACKTEST_ARTIFACT_CONTRACT_VERSION,
    BACKTEST_ARTIFACT_ENGINE_SCOPE,
    BACKTEST_ARTIFACT_ENGINE_VERSION,
    BacktestArtifactBundle,
    BacktestArtifactError,
    BacktestArtifactKind,
    BacktestArtifactState,
    BacktestOutputArtifact,
    publish_backtest_artifact_bundle,
)
from serenity_alpha_lab.quant.backtest.ledger import (
    PORTFOLIO_LEDGER_CONTRACT_VERSION,
    PORTFOLIO_LEDGER_SCHEMA_NAME,
    PORTFOLIO_LEDGER_SCHEMA_VERSION,
    ExecutionRecord,
    LedgerEvent,
    LedgerEventType,
    PortfolioLedger,
    PortfolioLedgerError,
    PositionLot,
)
from serenity_alpha_lab.quant.backtest.orders import (
    ORDER_STATE_MACHINE_CONTRACT_VERSION,
    ORDER_STATE_MACHINE_SCHEMA_NAME,
    ORDER_STATE_MACHINE_SCHEMA_VERSION,
    Order,
    OrderEvent,
    OrderEventType,
    OrderIntent,
    OrderSide,
    OrderStateMachineError,
    OrderStatus,
    OrderType,
    TERMINAL_ORDER_STATUSES,
    TimeInForce,
)
from serenity_alpha_lab.quant.backtest.spec import (
    BACKTEST_SPEC_CONTRACT_VERSION,
    BACKTEST_SPEC_ENGINE_VERSION,
    BACKTEST_SPEC_SCHEMA_NAME,
    BACKTEST_SPEC_SCHEMA_VERSION,
    BacktestCostSpec,
    BacktestDatasetSpec,
    BacktestExecutionSpec,
    BacktestRiskSpec,
    BacktestSpec,
    BacktestSpecError,
    BacktestStrategySpec,
    BacktestUniverseSpec,
)

__all__ = [
    "BACKTEST_ARTIFACT_BUNDLE_CONTENT_TYPE",
    "BACKTEST_ARTIFACT_BUNDLE_SCHEMA_NAME",
    "BACKTEST_ARTIFACT_BUNDLE_SCHEMA_VERSION",
    "BACKTEST_ARTIFACT_CONTRACT_VERSION",
    "BACKTEST_ARTIFACT_ENGINE_SCOPE",
    "BACKTEST_ARTIFACT_ENGINE_VERSION",
    "BACKTEST_COST_MODEL_CONTRACT_VERSION",
    "BACKTEST_COST_MODEL_SCHEMA_NAME",
    "BACKTEST_COST_MODEL_SCHEMA_VERSION",
    "BACKTEST_COST_MODEL_VERSION",
    "A_SHARE_EXECUTION_MODEL_CONTRACT_VERSION",
    "A_SHARE_EXECUTION_MODEL_SCHEMA_NAME",
    "A_SHARE_EXECUTION_MODEL_SCHEMA_VERSION",
    "A_SHARE_EXECUTION_MODEL_VERSION",
    "BACKTEST_SPEC_CONTRACT_VERSION",
    "BACKTEST_SPEC_ENGINE_VERSION",
    "BACKTEST_SPEC_SCHEMA_NAME",
    "BACKTEST_SPEC_SCHEMA_VERSION",
    "ORDER_STATE_MACHINE_CONTRACT_VERSION",
    "ORDER_STATE_MACHINE_SCHEMA_NAME",
    "ORDER_STATE_MACHINE_SCHEMA_VERSION",
    "PORTFOLIO_LEDGER_CONTRACT_VERSION",
    "PORTFOLIO_LEDGER_SCHEMA_NAME",
    "PORTFOLIO_LEDGER_SCHEMA_VERSION",
    "BacktestArtifactBundle",
    "BacktestArtifactError",
    "BacktestArtifactKind",
    "BacktestArtifactState",
    "BacktestCostSpec",
    "BacktestDatasetSpec",
    "BacktestExecutionSpec",
    "BacktestOutputArtifact",
    "BacktestRiskSpec",
    "BacktestSpec",
    "BacktestSpecError",
    "BacktestStrategySpec",
    "BacktestUniverseSpec",
    "AShareExecutionAuditRecord",
    "AShareExecutionError",
    "AShareExecutionModel",
    "AShareExecutionOutcome",
    "AShareExecutionResult",
    "AShareExecutionStatus",
    "AShareMarketSnapshot",
    "ASharePositionAvailability",
    "CostBreakdown",
    "CostLineItem",
    "CostLineItemName",
    "CostModel",
    "CostModelError",
    "ExecutionRecord",
    "LedgerEvent",
    "LedgerEventType",
    "Order",
    "OrderEvent",
    "OrderEventType",
    "OrderIntent",
    "OrderSide",
    "OrderStateMachineError",
    "OrderStatus",
    "OrderType",
    "PortfolioLedger",
    "PortfolioLedgerError",
    "PositionLot",
    "TERMINAL_ORDER_STATUSES",
    "TimeInForce",
    "publish_backtest_artifact_bundle",
]
