"""Evidence, citation, claim and report schema contracts."""

from serenity_alpha_lab.evidence.schema import (
    EVIDENCE_CONTRACT_VERSION,
    EVIDENCE_SCHEMA_NAME,
    EVIDENCE_SCHEMA_VERSION,
    RESEARCH_CLAIM_CONTRACT_VERSION,
    RESEARCH_CLAIM_SCHEMA_NAME,
    RESEARCH_CLAIM_SCHEMA_VERSION,
    RESEARCH_REPORT_CONTRACT_VERSION,
    RESEARCH_REPORT_SCHEMA_NAME,
    RESEARCH_REPORT_SCHEMA_VERSION,
    ClaimComputationPolicy,
    ClaimKind,
    ClaimVerificationStatus,
    EvidenceEvaluationScope,
    EvidenceKind,
    EvidenceRecord,
    EvidenceSchemaError,
    EvidenceSource,
    EvidenceTrustLevel,
    ReportCitation,
    ResearchClaim,
    ResearchReport,
    ResearchReportLevel,
    evidence_json_schemas,
    quant_evidence_source_matrix,
)

__all__ = [
    "EVIDENCE_CONTRACT_VERSION",
    "EVIDENCE_SCHEMA_NAME",
    "EVIDENCE_SCHEMA_VERSION",
    "RESEARCH_CLAIM_CONTRACT_VERSION",
    "RESEARCH_CLAIM_SCHEMA_NAME",
    "RESEARCH_CLAIM_SCHEMA_VERSION",
    "RESEARCH_REPORT_CONTRACT_VERSION",
    "RESEARCH_REPORT_SCHEMA_NAME",
    "RESEARCH_REPORT_SCHEMA_VERSION",
    "ClaimComputationPolicy",
    "ClaimKind",
    "ClaimVerificationStatus",
    "EvidenceEvaluationScope",
    "EvidenceKind",
    "EvidenceRecord",
    "EvidenceSchemaError",
    "EvidenceSource",
    "EvidenceTrustLevel",
    "ReportCitation",
    "ResearchClaim",
    "ResearchReport",
    "ResearchReportLevel",
    "evidence_json_schemas",
    "quant_evidence_source_matrix",
]
