"""Application use-case orchestration boundary."""

from serenity_alpha_lab.application.api_errors import (
    ApiErrorCode,
    ApiProblemError,
    ConflictProblem,
    InternalProblem,
    NotFoundProblem,
    ProblemDetail,
    ProblemDetailsMiddleware,
    ProviderProblem,
    ValidationProblem,
    problem_from_exception,
    problem_response_body,
    problem_type_uri,
    redact_problem_detail,
)
from serenity_alpha_lab.application.candidate_batch import (
    CANDIDATE_BATCH_CONTRACT_VERSION,
    CANDIDATE_BATCH_SCHEMA_NAME,
    CANDIDATE_BATCH_SCHEMA_VERSION,
    Candidate,
    CandidateBatch,
    CandidateBatchError,
    CandidateLayerScore,
    CandidateReason,
    CandidateScoreLayer,
    CandidateSource,
    CandidateSourceType,
    candidate_batch_from_screening_result,
)
from serenity_alpha_lab.application.config_profiles import (
    ConfigProfileError,
    ConfigValueSource,
    ProfilePolicy,
    RuntimeConfigUpdatePreview,
    RuntimeProfile,
    RuntimeSettings,
    load_runtime_settings,
    preview_runtime_config_update,
    profile_policy,
    redacted_config_diagnostics,
)
from serenity_alpha_lab.application.research_orchestrator import (
    ProgressCallback,
    ResearchChatRequest,
    ResearchMode,
    ResearchOrchestrator,
    ResearchOrchestratorError,
    ResearchRequest,
    ResearchResult,
)
from serenity_alpha_lab.application.screening_provider import (
    SCREENING_PROVIDER_CONTRACT_VERSION,
    SCREENING_RAW_RESULT_SCHEMA_NAME,
    SCREENING_RAW_RESULT_SCHEMA_VERSION,
    FakeScreeningProvider,
    ScreeningProvider,
    ScreeningProviderError,
    ScreeningProviderErrorCategory,
    ScreeningProviderStatus,
    ScreeningRequest,
    ScreeningResult,
    ScreeningStrategy,
)
from serenity_alpha_lab.application.task_backend import (
    InMemoryTaskBackend,
    TaskAlreadyExists,
    TaskBackend,
    TaskBackendCapabilityError,
    TaskBackendError,
    TaskCommand,
    TaskEvent,
    TaskNotFound,
    TaskRef,
    TaskSnapshot,
    TaskStatus,
)
from serenity_alpha_lab.application.tracing import (
    StructuredLogFormatter,
    TraceContext,
    TraceContextFilter,
    TraceContextMiddleware,
    current_trace_context,
    generate_trace_id,
    redact_sensitive_data,
    use_trace_context,
)

__all__ = [
    "ApiErrorCode",
    "ApiProblemError",
    "CANDIDATE_BATCH_CONTRACT_VERSION",
    "CANDIDATE_BATCH_SCHEMA_NAME",
    "CANDIDATE_BATCH_SCHEMA_VERSION",
    "Candidate",
    "CandidateBatch",
    "CandidateBatchError",
    "CandidateLayerScore",
    "CandidateReason",
    "CandidateScoreLayer",
    "CandidateSource",
    "CandidateSourceType",
    "ConflictProblem",
    "ConfigProfileError",
    "ConfigValueSource",
    "InternalProblem",
    "NotFoundProblem",
    "ProblemDetail",
    "ProblemDetailsMiddleware",
    "ProviderProblem",
    "ProfilePolicy",
    "RuntimeConfigUpdatePreview",
    "RuntimeProfile",
    "RuntimeSettings",
    "ValidationProblem",
    "ProgressCallback",
    "BACKTEST_RUN_ORCHESTRATOR_CONTRACT_VERSION",
    "BACKTEST_RUN_ORCHESTRATOR_VERSION",
    "BACKTEST_RUN_SCHEMA_NAME",
    "BACKTEST_RUN_SCHEMA_VERSION",
    "BACKTEST_RUN_SUMMARY_CONTENT_TYPE",
    "BACKTEST_RUN_TYPE",
    "QUANT_SCREENING_API_CONTRACT_VERSION",
    "QUANT_SCREENING_API_ROUTES",
    "QUANT_SCREENING_COMPARISON_SCHEMA_NAME",
    "QUANT_SCREENING_COMPARISON_SCHEMA_VERSION",
    "QUANT_SCREENING_RUN_TASK_TYPE",
    "InMemoryQuantScreeningRepository",
    "QuantApiResponse",
    "QuantApiRoute",
    "QuantScreeningApiError",
    "QuantScreeningApiService",
    "QuantScreeningRunMode",
    "QuantScreeningRunRecord",
    "QuantScreeningRunRequest",
    "ResearchChatRequest",
    "ResearchMode",
    "ResearchOrchestrator",
    "ResearchOrchestratorError",
    "ResearchRequest",
    "ResearchResult",
    "BacktestRunCodeState",
    "BacktestRunMode",
    "BacktestRunOrchestrator",
    "BacktestRunOrchestratorError",
    "BacktestRunRecord",
    "BacktestRunRequest",
    "BacktestRunStageRecord",
    "BacktestRunStatus",
    "SCREENING_PROVIDER_CONTRACT_VERSION",
    "SCREENING_RAW_RESULT_SCHEMA_NAME",
    "SCREENING_RAW_RESULT_SCHEMA_VERSION",
    "FakeScreeningProvider",
    "ScreeningProvider",
    "ScreeningProviderError",
    "ScreeningProviderErrorCategory",
    "ScreeningProviderStatus",
    "ScreeningRequest",
    "ScreeningResult",
    "ScreeningStrategy",
    "candidate_batch_from_screening_result",
    "problem_from_exception",
    "problem_response_body",
    "problem_type_uri",
    "load_runtime_settings",
    "preview_runtime_config_update",
    "profile_policy",
    "redacted_config_diagnostics",
    "InMemoryTaskBackend",
    "InMemoryBacktestRunRepository",
    "TaskAlreadyExists",
    "TaskBackend",
    "TaskBackendCapabilityError",
    "TaskBackendError",
    "TaskCommand",
    "TaskEvent",
    "TaskNotFound",
    "TaskRef",
    "TaskSnapshot",
    "TaskStatus",
    "StructuredLogFormatter",
    "TraceContext",
    "TraceContextFilter",
    "TraceContextMiddleware",
    "current_trace_context",
    "generate_trace_id",
    "redact_problem_detail",
    "redact_sensitive_data",
    "use_trace_context",
]

_LAZY_EXPORTS = {
    "BACKTEST_RUN_ORCHESTRATOR_CONTRACT_VERSION": "serenity_alpha_lab.application.backtest_run",
    "BACKTEST_RUN_ORCHESTRATOR_VERSION": "serenity_alpha_lab.application.backtest_run",
    "BACKTEST_RUN_SCHEMA_NAME": "serenity_alpha_lab.application.backtest_run",
    "BACKTEST_RUN_SCHEMA_VERSION": "serenity_alpha_lab.application.backtest_run",
    "BACKTEST_RUN_SUMMARY_CONTENT_TYPE": "serenity_alpha_lab.application.backtest_run",
    "BACKTEST_RUN_TYPE": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunCodeState": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunMode": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunOrchestrator": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunOrchestratorError": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunRecord": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunRequest": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunStageRecord": "serenity_alpha_lab.application.backtest_run",
    "BacktestRunStatus": "serenity_alpha_lab.application.backtest_run",
    "InMemoryBacktestRunRepository": "serenity_alpha_lab.application.backtest_run",
    "QUANT_SCREENING_API_CONTRACT_VERSION": "serenity_alpha_lab.application.quant_screening_api",
    "QUANT_SCREENING_API_ROUTES": "serenity_alpha_lab.application.quant_screening_api",
    "QUANT_SCREENING_COMPARISON_SCHEMA_NAME": "serenity_alpha_lab.application.quant_screening_api",
    "QUANT_SCREENING_COMPARISON_SCHEMA_VERSION": "serenity_alpha_lab.application.quant_screening_api",
    "QUANT_SCREENING_RUN_TASK_TYPE": "serenity_alpha_lab.application.quant_screening_api",
    "InMemoryQuantScreeningRepository": "serenity_alpha_lab.application.quant_screening_api",
    "QuantApiResponse": "serenity_alpha_lab.application.quant_screening_api",
    "QuantApiRoute": "serenity_alpha_lab.application.quant_screening_api",
    "QuantScreeningApiError": "serenity_alpha_lab.application.quant_screening_api",
    "QuantScreeningApiService": "serenity_alpha_lab.application.quant_screening_api",
    "QuantScreeningRunMode": "serenity_alpha_lab.application.quant_screening_api",
    "QuantScreeningRunRecord": "serenity_alpha_lab.application.quant_screening_api",
    "QuantScreeningRunRequest": "serenity_alpha_lab.application.quant_screening_api",
}


def __getattr__(name: str) -> object:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value
